build:
    image: kradalby/ci-tox:latest
    pull: true
    commands:
      - apt-get update
      - apt-get install node npm
      - apt-get install wkhtmltopdf -y --force-yes
      - npm install fluentcv -g
      - npm install jsonresume-theme-slick
      - fluentcv BUILD resume.json TO out/cv.all -t node_modules/jsonresume-theme-slick
        # This is a hack...
      - perl -pi -E 's/link href="http/link href="https/g' out/cv.html
      - perl -pi -E "s/link href='http/link href='https/g" out/cv.html
      - echo "Deploying"

notify:
  email:
    from: drone@fap.no
    host: smtp.stud.ntnu.no
    port: 25
    recipients:
      - kradalby@kradalby.no

deploy:
  rsync:
    user: root
    host: seel.fap.no
    port: 22
    source: out/
    target: /srv/www/kradalby.no/pub/jobb/
    delete: false
    recursive: true
    exclude:
    when:
        branch: master
    commands:
      - echo "Done"
